### PR TITLE
Removed the unnecessary $

### PR DESCRIPTION
**Pull request by VottusCode**

### CODE REVIEW

**Comment by f3l1x** [comment]
Hey, thanks, but its intended. Anyway, we're working on new version. Would you be interested in collaboration? We're looking for some help and you look passioned about Nette and Vue.

**Comment by VottusCode** [comment]
> Hey, thanks, but its intended. Anyway, we're working on new version. Would you be interested in collaboration? We're looking for some help and you look passioned about Nette and Vue.

Sure, I'm down. You can hmu on Messenger, probably most active there :+1:

**Comment by VottusCode** [comment]
> Hey, thanks, but its intended. 
IMO many people will take it as if you did a typo while writing Latte

> Anyway, we're working on new version. Would you be interested in collaboration? We're looking for some help and you look passioned about Nette and Vue.
Sure, I'm down. You can hmu on Messenger, probably most active there :+1:

**Comment by f3l1x** [comment]
Componette is reworked. I am closing it here. We will reach you.

**Pull request closed without merging**
